tasks:
  - before: >
        mkdir -p ~/.ssh &&
        [[ ! -z $GP_SSH_SIGNING_KEY  ]] &&
        echo $GP_SSH_SIGNING_KEY > ~/.ssh/id_rsa.pub &&
        chmod 644 ~/.ssh/id_rsa.pub &&
        [[ ! -z $GP_SSH_SIGNING_PRIVKEY  ]] &&
        echo $GP_SSH_SIGNING_PRIVKEY | base64 -d > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa
  - name: Init webgoat
    init: docker pull webgoat/webgoat
    command: docker run -it -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 webgoat/webgoat  

ports:
  - name: webgoat-app
    description: Webgoat App 
    port: 8080
    visibility: private
    onOpen: open-preview
  - name: webgoat-app-backend
    description: Webgoat App Backend
    port: 9090
    visibility: private
    onOpen: open-preview

gitConfig:
    gpg.format: ssh
    commit.gpgsign: "true"
    user.signingkey: ~/.ssh/id_rsa.pub

vscode:
    extensions:
        - ms-python.python
        - ritwickdey.LiveServer